### ISSUE TITLE
Update ipyleaflet version to 0.10

### ISSUE THREAD

**Issue by TheBear44** [QuantStack/xleaflet#71]
Latest ipyleaflet/jupyter-leaflet release: `0.10.1`
Current semver requirement for jupyter-leaflet : `0.9.1`

https://github.com/QuantStack/xleaflet/blob/d1f606eb4d8a5fed5f4ef6effecffe7c8e97898d/include/xleaflet/xleaflet_config.hpp#L35-L38

**Comment by SylvainCorlay** [comment]
Yep, please use that older version of jupyter-leaflet as we have not updated it yet.
